### ISSUE TITLE
adding modeless editor

### ISSUE THREAD

**Issue by jlrn7** [pclouds/busybox-w32#21]
Hello! I'm trying to add `ue` as a modeless editor besides `vi` and I followed the instructions given in [the main busybox page](https://busybox.net/FAQ.html#adding) to include it, but somehow it didn't work. How can I share it to troubleshoot it? Thanks in advance,

**Comment by pclouds** [comment]
You should really open this issue on rmyorston fork, https://github.com/rmyorston/busybox-w32 as I'm not active in busybox-w32 anymore
